version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "poem-gpt-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3m8r5kydfet4"
s3_prefix = "poem-gpt-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
