service: poem-gpt
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 29 # optional, in seconds, default is 6
  stage: dev
  profile: ads

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: post
plugins:
  - serverless-offline
